[
  { id: 'me',
    label : 'Wes',
    title : 'Wes M. Williams',
    summary : '10+ years of development, support, administration, and integration of various database applications.', 
    content : 'I am a data-oriented developer interested in analyzing, modeling, integrating, and processing of business data in order to support operations and decision making. Since 2002 I have worked primarily on the back-end development of business systems. My work has always included database development and administration duties for OLTP systems. My technical strengths include data manipulation and integration, and I enjoy the challenges of data conversion and migration. I have interest in working in a data warehousing environment where my interest and strengths will be aligned with business needs.<br /><br /><a target="_blank" href="http://www.linkedin.com/in/wesmwilliams">Contact via LinkedIn</a>',
    imageUrl : 'images/resume/me.jpg',
    relations : ['home','school','work','skills','online','tech-favorites','interest']
  },
  { id: 'home',
    label : 'Home Life',
    title : 'I care about more than work...', 
    summary : 'I live in the Denver area with my wife and two dogs.', 
    content : 'CONTENT GOES HERE............................',
    imageUrl : null,
    relations : ['wife','dogs']
  },
  { id: 'work',
    label : 'Work Life',
    title : 'I develop software...', 
    summary : "I have developed software for 10+ years.", 
    content : 'CONTENT GOES HERE.............................',
    imageUrl : null, 
    relations : ['tech-core','worked-at']
  },
  { id: 'worked-at',
    label : 'Companies',
    title : "I have worked a few places...", 
    summary : "Most of my experience is in education.", 
    content : 'CONTENT GOES HERE.............................',
    imageUrl : null, 
    relations : ['work-cde','work-avow','work-stcc','work-sigad','work-desoto']
  },
  { id: 'work-desoto',
    label : 'Desoto Systems',
    title : 'Desoto Systems', 
    summary : 'I was a Software Developer at Desoto Systems from 2002 to 2004. I was responsible for creating web and desktop solutions for Windows and Unix platforms using Java, XML, and SQL databases.', 
    content : '<ul><li>Web Services  -  Java, XML, DTD</li><li>Web Applications  -  Java, Servlets/JSP, Javascript, CSS</li><li>Desktop Applications  -  Java, Swing</li><li>Database Development  -  PostgreSQL, SQL Server, SQL, pl/pgSQL</li><li>Database Administration  -  PostgreSQL<li>Automation & Integration  -  Shell Scripting</li>',
    imageUrl : null, 
    relations : ['tech-java','tech-xml']
  },
  { id: 'work-sigad',
    label : 'Signature Ad',
    title : 'Signature Advertising', 
    summary : 'I was a Software Developer at Signature Advertising from 2004 to 2006.', 
    content : 'CONTENT GOES HERE.............................',
    imageUrl : null, 
    relations : ['tech-java']
  },
  { id: 'work-stcc',
    label : 'STCC',
    title : 'Southwest TN Community College', 
    summary : 'I was a Systems Analyst at Southwest TN Community College from 2006 to 2008, and I switched to a database administrator role from 2008 to 9/2009.', 
    content : 'CONTENT GOES HERE.............................',
    imageUrl : null, 
    relations : ['tech-java','tech-oracle']
  },
  { id: 'work-avow',
    label : 'Avow Systems',
    title : 'Avow Systems', 
    summary : 'I was a Software Developer at Avow Systems from 10/2009 to 10/2011.', 
    content : 'CONTENT GOES HERE.............................',
    imageUrl : null, 
    relations : ['tech-java','tech-xml']
  },
  { id: 'work-cde',
    label : 'CDE',
    title : 'CO Dept. of Education', 
    summary : 'I have been a Software Developer at Colorado Department of Education since 10/2011.', 
    content : 'CONTENT GOES HERE.............................',
    imageUrl : null, 
    relations : ['tech-java','tech-xml','tech-oracle']
  },
  { id: 'wife',
    label : 'My Wife',
    title : 'I am married...', 
    summary : 'My wife and I married a few years ago.', 
    content : 'CONTENT GOES HERE..............................',
    imageUrl : null, 
    relations : []
  },
  { id: 'dogs',
    label : 'My Dogs',
    title : 'I have dogs...', 
    summary : 'Walking dogs is my primary form of exercise.', 
    content : 'CONTENT GOES HERE..............................',
    imageUrl : null,
    relations : []
  },
  { id: 'interest',
    label : 'Personal Interest',
    title : 'I enjoy several sports...', 
    summary : "I have always enjoyed fishing and college basketball, but I've taken a liking to skiing and Broncos football.", 
    content : 'CONTENT GOES HERE..............................',
    imageUrl : null, 
    relations : ['sports-skiing','sports-fishing','sports-football','sports-basketball']
  },
  { id: 'sports-basketball',
    label : 'Basketball',
    title : 'I enjoy college basketball...', 
    summary : "I have always enjoyed college basketball.", 
    content : 'CONTENT GOES HERE..............................',
    imageUrl : null, 
    relations : []
  },
  { id: 'sports-football',
    label : 'Broncos',
    title : 'I follow the Broncos...', 
    summary : "I've recently taken a liking to Broncos football.", 
    content : 'CONTENT GOES HERE..............................',
    imageUrl : null, 
    relations : []
  },
  { id: 'sports-fishing',
    label : 'Fishing',
    title : 'I would like to fish more...', 
    summary : "I have fished my whole life, and I plan to do more of it in Colorado in the future.", 
    content : 'CONTENT GOES HERE..............................',
    imageUrl : null, 
    relations : []
  },
  { id: 'sports-skiing',
    label : 'Skiing',
    title : 'I ski when I can...', 
    summary : "Skiing is fun, but I don't claim to be good at it.", 
    content : 'CONTENT GOES HERE...............................',
    imageUrl : null, 
    relations : []
  },
  { id: 'school',
    label : 'Education',
    title : 'I went to college...', 
    summary : 'I completed an associate and bachelor degree..', 
    content : 'CONTENT GOES HERE...............................',
    imageUrl : null, 
    relations : ['school-stcc','school-memphis','school-coursera']
  },
  { id: 'school-stcc',
    label : 'Associate Degree',
    title : 'I have an associate degree...', 
    summary : 'I attended Southwest TN Community College.', 
    content : 'CONTENT GOES HERE...............................',
    imageUrl : null,
    relations : []
  },
  { id: 'school-memphis',
    label : 'Bachelor Degree',
    title : 'I have a bachelor degree...', 
    summary : 'I attended the University of Memphis.', 
    content : 'CONTENT GOES HERE..............................',
    imageUrl : null, 
    relations : []
  },
  { id: 'school-coursera',
    label : 'Continuing Education',
    title : 'I do continuing education....', 
    summary : 'I currently take courses online via Coursera.', 
    content : 'CONTENT GOES HERE.............................',
    imageUrl : null, 
    relations : []
  },
  { id: 'online',
    label : 'Online Presence',
    title : 'I do stuff online...', 
    summary : 'I do lots of stuff online.', 
    content : 'CONTENT GOES HERE.............................',
    imageUrl : null, 
    relations : []
  },
  { id: 'software',
    label : 'Software Tools',
    title : 'I use various software tools...', 
    summary : 'I use various tools to accomplish my development work.', 
    content : '<img align="center" src="images/resume/career_pie.png" />',
    imageUrl : null, 
    relations : ['tech-subversion','tech-eclipse','tech-jdeveloper']
  },
  { id: 'skills',
    label : 'Tech Skills',
    title : 'I have tech skills...', 
    summary : 'I have worn many hats over my career.', 
    content : '<img align="center" src="images/resume/career_pie.png" />',
    imageUrl : null, 
    relations : ['skills-analysis','skills-databases','skills-integration','skills-development']
  },
  { id: 'skills-development',
    label : 'Development',
    title : 'I develop software...', 
    summary : "I'm primarily an integration developer", 
    content : '<img align="center" src="images/resume/programming_pie.png" />',
    imageUrl : null, 
    relations : ['tech-java','tech-xml','tech-oracle','tech-frameworks']
  },
  { id: 'skills-databases',
    label : 'Databases',
    title : 'I use databases.', 
    summary : 'Data is involved in everything I do.', 
    content : '<img align="center" src="images/resume/database_pie.png" />',
    imageUrl : null, 
    relations : ['tech-oracle','tech-mysql','tech-sqlserver','tech-postgresql']
  },
  { id: 'skills-integration',
    label : 'Integration',
    title : 'I integrate systems...', 
    summary : 'I use various methods to facilitate system integration.', 
    content : '<img align="center" src="images/resume/integration_pie.png" />',
    imageUrl : null, 
    relations : ['tech-xml','tech-json']
  },
  { id: 'skills-analysis',
    label : 'Analysis',
    title : 'I do analysis...', 
    summary : 'I enjoy approaching a problem without a known solution.', 
    content : 'CONTENT GOES HERE....................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-core',
    label : 'Core Toolset',
    title : 'I have notable experience with...', 
    summary : 'I have a wealth of experience with Oracle technologies.', 
    content : 'CONTENT GOES HERE....................',
    imageUrl : null, 
    relations : ['tech-xml','tech-java','tech-oracle']
  },
  { id: 'tech-favorites',
    label : 'Tech Radar',
    title : 'Tech on my radar...', 
    summary : 'I am interested in using APIs from single page web apps.', 
    content : 'CONTENT GOES HERE...................',
    imageUrl : null, 
    relations : ['tech-javascript','tech-json',]
  },
  { id: 'tech-frameworks',
    label : 'Frameworks',
    title : 'I use frameworks...', 
    summary : 'I am familar with many java frameworks.', 
    content : 'CONTENT GOES HERE..................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-java',
    label : 'Java',
    title : 'I am a java guru...', 
    summary : 'The JVM is my bread and butter.', 
    content : 'CONTENT GOES HERE..................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-javascript',
    label : 'Javascript',
    title : 'Javascript is fun...', 
    summary : "I have a renewed interest in javascript.", 
    content : 'CONTENT GOES HERE..................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-xml',
    label : 'XML',
    title : 'I exchange data in xml...', 
    summary : 'XML processing is one of my strengths.', 
    content : 'CONTENT GOES HERE...................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-json',
    label : 'JSON',
    title : 'I exchange data in JSON...', 
    summary : "It's hard to escape JSON when using javascript these days.", 
    content : 'CONTENT GOES HERE...................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-oracle',
    label : 'Oracle',
    title : 'I know the Oracle database well...', 
    summary : 'I am familar with the Oracle database from a developer and dba perspective.', 
    content : 'CONTENT GOES HERE...................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-mysql',
    label : 'MySQL',
    title : "I've used MySQL...", 
    summary : "I understand the different mindset that MySQL demands.", 
    content : 'CONTENT GOES HERE....................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-sqlserver',
    label : 'SQL Server',
    title : "I've used SQL Server...", 
    summary : "SQL Server has crossed my path, and I'm familar with how to work on it.",
    content : 'CONTENT GOES HERE...................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-postgresql',
    label : 'PostgreSQL',
    title : "I've used PostgreSQL...", 
    summary : 'My early work was primarily on PostgreSQL.', 
    content : 'CONTENT GOES HERE....................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-subversion',
    label : 'Subversion',
    title : "I've used Subversion...", 
    summary : 'I have used subversion most of my career.', 
    content : 'CONTENT GOES HERE....................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-eclipse',
    label : 'Eclipse IDE',
    title : "I've used the Eclipse IDE...", 
    summary : 'I have used Eclipse for most of my development career.', 
    content : 'CONTENT GOES HERE....................',
    imageUrl : null, 
    relations : []
  },
  { id: 'tech-jdeveloper',
    label : 'JDeveloper',
    title : "I've used JDeveloper...", 
    summary : 'I have been using JDeveloper recently..', 
    content : 'CONTENT GOES HERE....................',
    imageUrl : null, 
    relations : []
  }
]
